# Generated by Django 3.2.6 on 2021-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumnail', models.ImageField(upload_to='blog')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
