# Generated by Django 3.2.7 on 2021-09-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductInBasket',
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
