# Generated by Django 3.2.6 on 2021-09-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210907_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
