# Generated by Django 3.2.6 on 2021-09-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
