# Generated by Django 3.2.6 on 2021-09-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210909_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_optional',
        ),
    ]
