# Generated by Django 3.2.6 on 2021-09-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contact_subcribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subcribers',
            new_name='subcriber',
        ),
    ]
