# Generated by Django 3.2.6 on 2021-09-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_blog_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prod_img/')),
                ('title_1', models.CharField(max_length=600)),
                ('title_2', models.CharField(max_length=600)),
            ],
        ),
    ]
