# Generated by Django 3.2.6 on 2021-09-16 14:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '8. Banners'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name_plural': '4. Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '5. Contacts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '2. Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': '3. Order Items'},
        ),
        migrations.AlterModelOptions(
            name='subcriber',
            options={'verbose_name_plural': '6. Subcribers'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': '7. Testimonials'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='banners'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='blog'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='testimonials'),
        ),
    ]
